##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"
sequencingCenter: "Sequencing Center" # e.g.  sequencingCenter: "University_of_Washington_Genome_Sciences"

# Sample
sampleId: "<samplify sampleId>"                                         # e.g  sampleId: 123456
sampleDirectory: "<full path to sample directory>"                      # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleFastxQCDirectory: "<full path to fastx qc directory>"             # e.g. sampleFastxQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/fastqs/qc"
sampleMappedBamsDirectory: "<full path to mapped bam output directory>" # e.g. sampleMappedBamsDirectory: "/net/nwgc/vol1/data/processed/samples/123456/mappedBams"
sampleMappingQCDirectory: "<full path to mapping qc directory>"         # e.g. sampleMappingQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/mappedBams/qc"
sampleQCDirectory: "<full path to sample QC directory>"                 # e.g. sampleQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/qc"
samplePolymorphicQCDirectory: "<full path to sample QC directory>"      # e.g. samplePolymorphicQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/polymorphicQC"
isNovaseqQCPool: <true if sample is a Novaseq qc pool>                  # e.g. isNovaseqQCPool: true
novaseqQCPoolPlexity: <number of samples in the Novaseq qc pool>        # e.g. novaseqQCPoolPlexity: 100

# Target
sequencingTarget: "<name of sequencing target>"                      # e.g. sequencingTarget: "nimblegen_solution_V2refseq_2010"
sequencingTargetIntervalsList: "<full path to intervals.list file>"  # e.g. sequencingTargetIntervalsList: "/net/nwgc/vol1/references/human/grc38/targets/nimblegen_solution_V2refseq_2010/nimblegen_solution_V2refseq_2010.grc38.intervals.list"
targetListFile: "<full path to target .list file>"                   # e.g. targetListFile: "/net/nwgc/vol1/references/human/hg19/targets/nimblegen_solution_V2refseq_2010/nimblegen_solution_V2refseq_2010.hg19.list"
  # sequencingTargetIntervalsDirectory should be null unless running analysis by chromosome
sequencingTargetIntervalsDirectory: "<full path to directory with chromosome intervals list files>"  # e.g. sequencingTargetIntervalsDirectory: "/net/nwgc/vol1/references/human/grc38/targets/nimblegen_solution_V2refseq_2010"
sequencingTargetBedFile: "<full path to bed file>"                                                   # e.g sequencingTargetBedFile: "/net/nwgc/vol1/references/human/grc38/targets/nimblegen_solution_V2refseq_2010/nimblegen_solution_V2refseq_2010.grc38.bed"

# Reference Genome
referenceGenome: "<full path to reference genome fasta>"        # e.g. referenceGenome: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/hs37d5.fa"
dbSnp: "<full path to dbSnp file>"                              # e.g. dbSnp: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/Homo_sapiens_assembly38.dbsnp138.vcf" (grc38)
                                                                # e.g. dbSnp: "/net/nwgc/vol1/references/human/snps/dbSNP/dbSNP138.vcf" (hg19)
goldStandardIndels: "<full path to gold standard indels file>"  # e.g. goldStandardIndels: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/Mills_and_1000G_gold_standard.indels.hg38.vcf"
knownIndels: "<full path to known indels file>"                 # e.g. knownIndels: "/net/nwgc/vol1/references/human/rc38/genome/assembly_bwa_0.7.15/Homo_sapiens_assembly38.known_indels.vcf"
referenceAbbr: "<reference genome abbreviation>"                # e.g. referenceAbbr: "grc38"

# Fingerprint
fingerprintBedFile:	"<full path to fingerprint bed file>"			# e.g. fingerprintBed: "/net/nwgc/vol1/references/human/grc38/targets/fingerprint_grc38_open_array.bed"

# Contamination
  # Leave null to use default file path 
contaminationUDPath: "<full path to contamination UD file>"     # e.g. contaminationUDPath: "/net/nwgc/vol1/references/human/grc38/contamination/1000g.twist_plus_refseq_10-31-2018.AF1p.b38.vcf.gz.UD"
contaminationBedPath: "<full path to contamination Bed file>"   # e.g. contaminationBedPath: "/net/nwgc/vol1/references/human/grc38/contamination/1000g.twist_plus_refseq_10-31-2018.AF1p.b38.vcf.gz.bed"
contaminationMeanPath: "<full path to contamination Mean file>" # e.g. contaminationMeanPath: "/net/nwgc/vol1/references/human/grc38/contamination/1000g.twist_plus_refseq_10-31-2018.AF1p.b38.vcf.gz.mu"
  # Custom contamination target
isCustomContaminationTargetSample: "<true or false based on if the sample has a custom contamination target>" #e.g. isCustomTargetContaminationSample: true
customContaminationTargetReferenceVCF: "<full path to VCF file for a custom contamination target>"            #e.g. customTargetContaminationReferenceVCF: "/net/nwgc/vol1/references/human/hg19/snps/verifyBamId/hapmap_3.3.b37.sites.vcf"


# Semi optional input files. Each yaml should have exactly one of mappedBams, mergedBam, or filteredGVCF depending on the portion of the pipeline meant to run.
# Each is null by default

# LibraryInfo - List of fastq files that need mapping and associated (optional) read group info
flowCellLaneLibraries:
  - fastq1: "<full path to the fastq1 file>"
    fastq2: "<full path to the fastq2 file>"
    flowCell: "<flow cell name>"
    lane: "<flow cell lane number>"
    library: "<library id>"
    runDate: "<iso formatted date the flow cell was run on the sequencer>"
    readLength: "<The read length for the given fastq files>"
    readType: "<The read type for the given fastq files>" # Optional input defaulted to PE (Paired End). Can be overriden to SR or SE (Single Read/ End).
    sequencingPlatform: "<sequencing platform of the flow cell>" # Optional input defaulted to Illumina
  - fastq1: "<full path to the fastq1 file>"
    fastq2: "<full path to the fastq2 file>"
    flowCell: "<flow cell name>"
    lane: "<flow cell lane number>"
    library: "<library id>"
    runDate: "<iso formatted date the flow cell was run on the sequencer>"
    readLength: <The read length for the given fastq files>
    readType: "<The read type for the given fastq files>" # Optional input defaulted to PE (Paired End). Can be overriden to SR or SE (Single Read/ End).
    sequencingPlatform: "<sequencing platform of the flow cell>"
  # Continue for all sample flowcell lane libraries

# mappedBams  - Bam files that have been mapped (to merge together)
mappedBams:
  - bam: "<full path to first mapedBam>"
    bai: "<full path to first mapedBai (mappedBam.bai)>"
    flowcell: "<flowcell>"
    lane: "<lane>"
    library: "<libraryId>"
  - bam: "<full path to second mapedBam>"
    bai: "<full path to second mapedBai (mappedBam.bai)>"
    flowcell: "<flowcell2>"
    lane: "<lane2>"
    library: "<libraryId2>"
  # Continue for all sample mapped bams

# e.g.
#mappedBams:
#  - "/net/nwgc/vol1/home/kolart/nextflow_library_merge_test/downsampled_1.bam"
#  - "/net/nwgc/vol1/home/kolart/nextflow_library_merge_test/downsampled_2.bam"

# mergedBam (for running qc on an already existing merged bam)
mergedBam: "<full path to a merged bam that contains nm tags>"
# e.g.
#mergedBam: /net/nwgc/vol1/home/kolart/pacbio_merged_test.bam

# filteredGVCF (for running polymorphic qc on already a smaple with variants already called)
filteredGVCF: "<full path to a filtered_gvcf file>" # e.g. /net/nwgc/vol1/home/kolart/

# camsForReprocessing - Cram files and their references to be split back into fastqs and completely reprocessed
cramsForReprocessing:
  - cram: "<full path to first cram>", 
    reference: "<full path to first cram reference file>"
  - cram: "<full path to second cram>", 
    reference: "<full path to second cram reference file>"
  # continue for all crams

# bamsForReprocessing - Bam files to be split back into fastqs and completely reprocessed
bamsForReprocessing: 
  - "<full path to first bam>"
  - "<full path to second bam>"
  # continue for all bams

# samToFastqValidationStringency - optional value if need to silence samToFastq errors
samToFastqValidationStringency: "SILENT"

# externalFastqs - fastq files that have no associated FCLL information to be reprocessed.
#                  If the library id is left out it will be assumed that all fastqs are from the same library.
externalFastqs: 
  - fastq1: "<full path to first fastq read 1>"
    fastq2: "<full path to first fastq read 2>"
    library: "<optional library id>"
  - fastq1: "<full path to second fastq read 1>"
    fastq2: "<full path to second fastq read 2>"
    library: "<optional library id>"


# Optional (Already defaulted in nextflow.config file to organism=Homo sapiens, isGRC38=false)
# Pipeline runs alls steps by default which is ["fastx_qc", "mapping", "mapping_qc", "merging", "qc", "variant_calling", "polymorphic_qc"]
# QC is defaulted to all steps which is ["coverage", "coverage_by_chrom", "contamination", "fingerprint", "picard_multiple_metrics", "samtools_flagstat", "samtools_stats", "collect_and_plot"]
# Mapping QC is defaulted to ["coverage", "coverage_by_chrom", "contamination", "picard_multiple_metrics", "samtools_flagstat", "samtools_stats"]
organism: "<species other than Homo sapiens>"  # e.g. organism: "Mus musculus"
isGRC38: "<true if grc38>"                     # e.g. isGRC38: true
pipelineStepsToRun: "[list of pipeline steps to run]"         # e.g ["merging", "qc", "variant_calling"]
qcToRunCustom: "[list of qc steps to run on the merged bam]"  # e.g ["coverage", "contamination", "picard_multiple_metrics", "samtools_flagstat", "samtools_stats"]
qcToRunMapping: "[list of qc steps to run on each mapped bam]"
