##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"       # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleQCDirectory: "<full path to sample QC directory>"  # e.g. sampleQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/qc"
sampleId: <samplify sampleId>                            # e.g sampleId: 123456
libraryId: <samplify library>                            # e.g libraryId: 123456

# Target
sequencingTarget: "<name of sequencing target>"   	  # e.g. sequencingTarget: "nimblegen_solution_V2refseq_2010"

# Reference Genome
referenceGenome: "<full path to reference genome fasta>"        # e.g. referenceGenome: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/hs37d5.fa"
dbSnp: "<full path to dbSnp file>"                              # e.g. dbSnp: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/Homo_sapiens_assembly38.dbsnp138.vcf"
goldStandardIndels: "<full path to gold standard indels file>"  # e.g. goldStandardIndels: "/net/nwgc/vol1/references/human/grc38/genome/assembly_bwa_0.7.15/Mills_and_1000G_gold_standard.indels.hg38.vcf"
knownIndels: "<full path to known indels file>"                 # e.g. knownIndels: "/net/nwgc/vol1/references/human/rc38/genome/assembly_bwa_0.7.15/Homo_sapiens_assembly38.known_indels.vcf"
fingerprintBed:	"<full path to known indels file>"				# e.g. fingerprintBed: "/net/nwgc/vol1/references/human/grc38/targets/fingerprint_grc38_open_array.bed"



# Bams  - Bam files that have been mapped (to merge together) 
mappedBams:
  - "<full path to first mapedBam>"
  - "<full path to second mappedBam>"
  - "<repeat for more bams>"
# e.g.
#bams:
#  - "/net/nwgc/vol1/home/kolart/nextflow_library_merge_test/downsampled_1.bam"
#  - "/net/nwgc/vol1/home/kolart/nextflow_library_merge_test/downsampled_2.bam"
